import { useState } from 'react';
import { Image, Sparkles, X, ChevronLeft, ChevronRight } from 'lucide-react';
import { ImageTile } from './Tile';
import img3dLogo from '../assets/3d-logo.png';
import imgDiagram from '../assets/diagram.png';
import imgPartnerJourney from '../assets/partner-journey-new.jpeg';
import imgOrig from '../assets/orig.png';
import imgParallax from '../assets/parallax-layered-scroll.jpg';
import imgDownload from '../assets/download.svg';
import imgGlassDashboard from '../assets/glassmorphic-app-dashboard.png';
import imgGlassIphone from '../assets/glassmorphic-iphone-floating.png';

const aiGallery = [
  { file: '01-bioluminescent-ocean.png', title: 'Bioluminescent Ocean', desc: 'Deep sea jellyfish, glowing blue and violet' },
  { file: '02-cyberpunk-city.png', title: 'Cyberpunk Cityscape', desc: 'Neon-lit streets, flying cars, Blade Runner vibes' },
  { file: '03-dewdrop-macro.png', title: 'Dewdrop Macro', desc: 'Landscape reflected inside a single droplet' },
  { file: '04-jungle-temple.png', title: 'Jungle Temple', desc: 'Ancient ruins swallowed by rainforest' },
  { file: '05-mars-astronaut.png', title: 'Mars at Dusk', desc: 'Lone astronaut facing a Martian dust storm' },
  { file: '06-portrait-elder.png', title: 'Portrait Study', desc: 'Candlelit hyperrealistic portrait' },
  { file: '07-supercell-storm.png', title: 'Supercell Storm', desc: 'Lightning and drama over the Great Plains' },
  { file: '08-butterfly-micro.png', title: 'Butterfly Microscopy', desc: 'Wing nanostructures up close' },
  { file: '09-baroque-library.png', title: 'Baroque Library', desc: 'Floor-to-ceiling books in golden light' },
  { file: '10-wolf-pack-snow.png', title: 'Wolf Pack', desc: 'Running through snow at blue hour' },
];

const capabilities = [
  'High-Res 3D Logo Generation',
  'Retro Pixel Art',
  'Parallax Art Layers',
  'Story-Driven Infographics',
  'Data Visualizations',
  'Glassmorphic 3D',
];

const images = [
  {
    title: 'High-Res 3D Logo',
    image: img3dLogo,
    url: null,
    category: '3D Design',
  },
  {
    title: 'Intricate Labeled Artifact Diagrams',
    image: imgDiagram,
    url: null,
    category: 'Data Viz',
  },
  {
    title: 'Partner Journey Infographic',
    image: imgPartnerJourney,
    url: null,
    category: 'Story Infographic',
  },
  {
    title: 'Pixelated Retro Artifacts',
    image: imgOrig,
    url: null,
    category: 'Art',
  },
  {
    title: 'Parallax Layered Scroll Artifacts',
    image: imgParallax,
    url: null,
    category: 'Branding',
  },
  {
    title: 'Network Topography Diagrams',
    image: imgDownload,
    url: null,
    category: 'Design',
  },
  {
    title: 'Glassmorphic App Interface',
    image: imgGlassDashboard,
    url: null,
    category: 'Glassmorphic 3D',
  },
  {
    title: 'Floating iPhone Concept',
    image: imgGlassIphone,
    url: null,
    category: 'Glassmorphic 3D',
  },
];

export default function ImagesInfographics() {
  const [lightbox, setLightbox] = useState(null);
  const prev = () => setLightbox(i => (i - 1 + aiGallery.length) % aiGallery.length);
  const next = () => setLightbox(i => (i + 1) % aiGallery.length);

  return (
    <section id="images" className="py-12 sm:py-20 lg:py-28 relative bg-slate-900/30 scroll-mt-36 sm:scroll-mt-40">
      {/* Background accent */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute bottom-0 left-1/4 w-[600px] h-[600px] bg-emerald-500/10 rounded-full blur-[150px]" />
      </div>

      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section header */}
        <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4 sm:gap-6 mb-8 sm:mb-12">
          <div>
            <div className="flex items-center gap-3 mb-3 sm:mb-4">
              <div className="p-2.5 rounded-xl bg-gradient-to-br from-emerald-400 to-cyan-500">
                <Image className="w-5 h-5 text-white" />
              </div>
              <span className="text-sm font-semibold text-emerald-400 uppercase tracking-wider">
                Visual Content
              </span>
            </div>
            <h2 className="text-2xl sm:text-4xl lg:text-5xl font-bold text-white mb-2 sm:mb-3">
              Images & Infographics
            </h2>
            <p className="text-slate-400 text-sm sm:text-lg max-w-xl mb-3 sm:mb-4">
              From brand assets and infographics to photorealistic scenes — all generated by AI.
            </p>
            <div className="flex flex-wrap gap-2">
              {capabilities.map((cap) => (
                <span
                  key={cap}
                  className="px-3 py-1 rounded-full text-xs font-medium bg-emerald-500/10 text-emerald-300 border border-emerald-500/20"
                >
                  {cap}
                </span>
              ))}
            </div>
          </div>

          <div className="flex items-center gap-2 text-sm text-slate-400">
            <Sparkles className="w-4 h-4 text-emerald-400" />
            <span>{images.length} images</span>
          </div>
        </div>

        {/* Image grid */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3 sm:gap-6">
          {images.map((img) => (
            <ImageTile key={img.title} {...img} />
          ))}
        </div>

        {/* AI Gallery sub-section */}
        <div className="mt-16 sm:mt-20">
          <div className="flex items-center gap-4 mb-8">
            <div className="h-px flex-1 bg-gradient-to-r from-transparent via-white/10 to-transparent" />
            <div className="flex items-center gap-2 px-4 py-1.5 rounded-full glass-card">
              <Sparkles className="w-3.5 h-3.5 text-cyber-cyan" />
              <span className="text-xs font-semibold text-slate-300 uppercase tracking-widest">Gemini 3 Pro · Pure AI Photography</span>
            </div>
            <div className="h-px flex-1 bg-gradient-to-r from-transparent via-white/10 to-transparent" />
          </div>

          <div className="columns-1 sm:columns-2 lg:columns-3 gap-4 space-y-4">
            {aiGallery.map((img, i) => (
              <div
                key={img.file}
                className="break-inside-avoid glass-card rounded-2xl overflow-hidden cursor-pointer group glass-hover"
                onClick={() => setLightbox(i)}
              >
                <div className="relative overflow-hidden">
                  <img
                    src={`/images/ai-gallery/${img.file}`}
                    alt={img.title}
                    className="w-full h-auto object-cover transition-transform duration-500 group-hover:scale-105"
                    loading="lazy"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                  <div className="absolute bottom-0 left-0 right-0 p-4 translate-y-2 opacity-0 group-hover:opacity-100 group-hover:translate-y-0 transition-all duration-300">
                    <p className="text-white font-semibold text-sm">{img.title}</p>
                    <p className="text-slate-300 text-xs mt-0.5">{img.desc}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Lightbox */}
      {lightbox !== null && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 backdrop-blur-sm"
          onClick={() => setLightbox(null)}
        >
          <button className="absolute top-4 right-4 p-2 rounded-full glass text-white hover:bg-white/10 transition-colors" onClick={() => setLightbox(null)}>
            <X className="w-6 h-6" />
          </button>
          <button className="absolute left-4 p-2 rounded-full glass text-white hover:bg-white/10 transition-colors" onClick={e => { e.stopPropagation(); prev(); }}>
            <ChevronLeft className="w-6 h-6" />
          </button>
          <div className="max-w-5xl max-h-[90vh] mx-12 flex flex-col items-center gap-4" onClick={e => e.stopPropagation()}>
            <img
              src={`/images/ai-gallery/${aiGallery[lightbox].file}`}
              alt={aiGallery[lightbox].title}
              className="max-h-[80vh] max-w-full object-contain rounded-xl shadow-2xl"
            />
            <div className="text-center">
              <p className="text-white font-semibold">{aiGallery[lightbox].title}</p>
              <p className="text-slate-400 text-sm">{aiGallery[lightbox].desc}</p>
            </div>
          </div>
          <button className="absolute right-4 p-2 rounded-full glass text-white hover:bg-white/10 transition-colors" onClick={e => { e.stopPropagation(); next(); }}>
            <ChevronRight className="w-6 h-6" />
          </button>
        </div>
      )}
    </section>
  );
}
